config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: "flats#index"
  resources :flats
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/flat.rb
class Flat < ApplicationRecord
  validates :name, presence: true
  validates :address, presence: true
  validates :description, presence: true
  validates :price_per_night, presence: true, numericality: { only_integer: true, greater_than: 0 }
  validates :number_of_guests, presence: true, numericality: { only_integer: true, greater_than: 0 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/flats_controller.rb
class FlatsController < ApplicationController
  before_action :set_flat, only:[:show, :edit, :update, :destroy]

  def index
    @query = params["query"]
    if @query
      @flats = Flat.where("name LIKE '%#{@query}%'")
    else
      @flats = Flat.all
    end

  end

  def show
  end

  def new
    @flat = Flat.new
  end

  def create
    @flat = Flat.create(flat_params)
    if @flat.save
      redirect_to flat_path(@flat)
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @flat.update(flat_params)
      @flat.update(flat_params)
      redirect_to flat_path(@flat)
    else
      render :new
    end
  end

  def destroy
    @flat.destroy
    redirect_to flats_path
  end

  private

  def flat_params
    params.require(:flat).permit(:name, :address, :description, :price_per_night, :number_of_guests)
  end

  def set_flat
    @flat = Flat.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/flats_helper.rb
module FlatsHelper
end

app/views/flats/_book-form.html.erb
<form>
  <div class="form-group">
    <div>
      <div class="input-group">
        <div class="input-group-prepend">
          <div class="input-group-text">From:</div>
        </div>
        <input id="from_date" name="from_date" type="text" class="form-control">
      </div>
    </div>
  </div>
  <div class="form-group">
    <div>
      <div class="input-group">
        <div class="input-group-prepend">
          <div class="input-group-text">To:</div>
        </div>
        <input id="to_date" name="to_date" type="text" class="form-control">
      </div>
    </div>
  </div>
  <div class="form-group">
    <div>
      <button name="submit" type="submit" class="btn btn-primary w-100">Book now</button>
    </div>
  </div>
</form>

app/views/flats/edit.html.erb
<h1>Edit flat details</h1>

<%= simple_form_for [@flat] do |f| %>
  <%= f.input :name %>
  <%= f.input :address %>
  <%= f.input :description %>
  <%= f.input :price_per_night %>
  <%= f.input :number_of_guests %>
  <%= f.submit "Submit", class: "btn btn-primary" %>
<% end %>

app/views/flats/index.html.erb
<h1>All our flats (<%= @flats.count %>)</h1>

<div class="cards">
  <% @flats.each do |flat| %>
    <div class="card">
      <div class="card-details">
        <h3><%= flat.name %></h3>
        <p><%= flat.address %></p>
      </div>
      <div class="card-links">
        <div class="card-link">
          <i class="fas fa-users"></i> <%= flat.number_of_guests %>
        </div>
        <div class="card-link">
          <i class="fas fa-euro-sign"></i> <%= flat.price_per_night %>
        </div>
      </div>
      <div class="card-footer">
      <%= link_to "More info", flat_path(flat) %>
      <%= link_to "Edit", edit_flat_path(flat), class: "ml-2 text-warning" %>
      <%= link_to "Delete", flat_path(flat), method: :delete, data: { confirm: "Are you sure?" }, class: "ml-2 text-danger" %>
      </div>
    </div>
  <% end %>
</div>

app/views/flats/new.html.erb
<h1>Add a flat</h1>

<%= simple_form_for [@flat] do |f| %>
  <%= f.input :name %>
  <%= f.input :address %>
  <%= f.input :description %>
  <%= f.input :price_per_night %>
  <%= f.input :number_of_guests %>
  <%= f.submit "Submit", class: "btn btn-primary" %>
<% end %>

app/views/flats/show.html.erb
  <div class="row">

    <div class="col-12 col-lg-8">
      <div class="flat-section">
        <h1><%= @flat.name %></h1>
        <p><%= @flat.address %></p>
      </div>

      <div class="flat-section">
        <h1>A bit more about this place...</h1>
        <p><%= @flat.description %></p>
      </div>

    </div>

    <div class="col-12 col-lg-4">
      <div class="flat-section">
        <p>Book this place</p>
        <%= render './flats/book-form' %>
      </div>
    </div>

  </div>

app/views/layouts/_navbar.html.erb
<div class="navbar-lewagon">
  <div class="mr-auto p-2">
    <%= link_to "Simple AirBnB", root_path %>
  </div>

  <!-- displayed on laptops -->
  <div class="p-2">
    <form>
      <div class="input-group">
        <input type="text" name="query" class="form-control" id="query" placeholder="<%= @query %>">
        <span class="input-group-btn">
          <button type="submit" class="btn btn-primary">Search</button>
        </span>
      </div>
     </div>
   </form>
  <div class="p-2">
    <%= link_to "Add Flat", new_flat_path, class: "btn btn-outline-primary" %>
  </div>


  <!-- displayed on phone / tablet -->
  <div class="navbar-lewagon-actions d-block d-sm-none">
    <div class="dropdown">
      <i class="fas fa-bars" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"></i>
      <div class="dropdown-menu dropdown-menu-right" aria-labelledby="dropdownMenuButton">
        <%= link_to "#", class: "dropdown-item" do %>
          <i class="fas fa-home"></i> Browse flats
        <% end %>
        <%= link_to "#", class: "dropdown-item" do %>
          <i class="fas fa-comments"></i> Messages <span class="badge badge-pill badge-secondary text-white">5</span>
        <% end %>
        <%= link_to "#", class: "dropdown-item" do %>
          <i class="fas fa-user"></i> Account
        <% end %>
        <%= link_to "#", class: "dropdown-item" do %>
          <i class="fas fa-cogs"></i> Settings
        <% end %>
        <%= link_to "#", class: "dropdown-item" do %>
          <i class="fas fa-sign-out-alt"></i> Log out
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsSimpleAirbnb</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

    <div>
      <%= render './layouts/navbar' %>
    </div>

    <div class="container">
      <%= yield %>
    </div>

  </body>
</html>